Update fz

diff --git a/fz b/fz
--- a/fz
+++ b/fz
@@ -16,7 +16,7 @@ help() {
             fi
         done)
         IFS=","
-        echo -e "\e[5;31mArgumen tidak valid\nPassed: ${invalidArgs[*]}\n\e[0m"
+        echo -e "\e[0;31mArgumen tidak valid\nPassed: ${invalidArgs[*]}\n\e[0m"
     fi
     echo -e "\e[1;32mScript-II by FZ Project\n\e[0m
 \e[5;33mPenggunaan: fz [OPSI]\n\e[0m
@@ -49,7 +49,7 @@ do
                         if ping -c 1 google.com >/dev/null 2>&1; then
                             cd "$path"/.. && rm -rf "$path" && git clone --depth=1 https://github.com/fzscript/Script-II.git && fz && exit
                         else
-                            echo -e "\e[5;37mTidak ada koneksi Internet!\e[0m"
+                            echo -e "\e[0;37mTidak ada koneksi Internet!\e[0m"
                             exit 1
                         fi
                         ;;
@@ -95,10 +95,10 @@ checkdependencies() {
         return 0
     else
         if ping -c 1 google.com >/dev/null 2>&1; then
-            installdependencies || (echo -e "\e[5;31mDependensi tidak diinstal!\e[0m" && exit 1)
+            installdependencies || (echo -e "\e[0;31mDependensi tidak diinstal!\e[0m" && exit 1)
         else
             cp "$path/fz" "$BIN/fz"
-            echo -e "\e[5;31mDependensi tidak diinstal!\n \e[5;37mJalankan kembali dengan koneksi Internet.\e[0m"
+            echo -e "\e[0;31mDependensi tidak diinstal!\n \e[0;37mJalankan kembali dengan koneksi Internet.\e[0m"
             exit 1
         fi
     fi
@@ -106,7 +106,7 @@ checkdependencies() {
 
 installdependencies() {
     clear
-    echo -e "\e[5;33mMenginstal dependensi...\e[0m"
+    echo -e "\e[0;33mMenginstal dependensi...\e[0m"
     arch=$(getprop ro.product.cpu.abi)
     cp "$path/fz" "$BIN/fz"
     sleep 1
@@ -117,7 +117,7 @@ installdependencies() {
     sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties"
     [ ! -f "$DATA/aapt2" ] && wget "https://github.com/decipher3114/termux-aapt/releases/download/v0.1/aapt2_$arch" -O "$DATA/aapt2" && chmod +x "$DATA/aapt2"
     [ ! -f "$DATA/pup" ] && wget "https://github.com/decipher3114/pup/releases/download/v0.1/pup_$arch" -O "$DATA/pup" && chmod +x "$DATA/pup"
-    echo -e "\e[5;32mDependensi berhasil diinstal.\e[0m"
+    echo -e "\e[0;32mDependensi berhasil diinstal.\e[0m"
     return 0
 }
 
@@ -127,7 +127,7 @@ checkscripts() {
         rm -rf ./*cache*
         return 0
     else
-        echo -e "\e[5;31mSkrip tidak ditemukan!\e[0m"
+        echo -e "\e[0;31mSkrip tidak ditemukan!\e[0m"
         echo "Apakah Anda ingin menginstal ulang?"
         read -r -p "[Y/N]: " choice
         case "$choice" in
@@ -143,7 +143,7 @@ checkscripts() {
             exit 0
             ;;
         ?)
-            echo -e "\e[5;31mOpsi tidak valid\e[0m"
+            echo -e "\e[0;31mOpsi tidak valid\e[0m"
             exit 1
             ;;
         esac
@@ -172,9 +172,9 @@ exitstatus=$?
 clear
 cd "$HOME" || :
 if [ $exitstatus -eq 0 ]; then
-    echo -e "\e[5;32mKeluar!\e[0m"
+    echo -e "\e[0;37mKeluar!\e[0m"
 else
-    echo -e "\e[5;31mSkrip dihentikan!\e[0m"
+    echo -e "\e[0;31mSkrip dihentikan!\e[0m"
     rm -rf -- *cache >/dev/null 2>&1
 fi
 tput cnorm
